"""
Django settings for medsupplies project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@h_=^0!lg2fs*)3&%ro2ej-gag%!p=gw7*a0!x8sz&u7igti6b'

# --- ⚠️ PRODUCTION SETTING ---
# SECURITY WARNING: Don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*'] # Allows access from any host on Render

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # --- ⚙️ WHITE NOISE SETTING 1 ---
    # Used to ensure WhiteNoise doesn't interfere with collectstatic locally, 
    # but still works in development with DEBUG=True
    'whitenoise.runserver_nostatic', 
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # --- ⚙️ WHITE NOISE SETTING 2: Must be right after SecurityMiddleware ---
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medsupplies.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'shop' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medsupplies.wsgi.application'

# Database
DATABASES = {
    'default': dj_database_url.config(default='sqlite:///db.sqlite3')
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# --- ⚙️ STATIC PATHS ---
# This is where collectstatic will put all files for Render to serve.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 
# This tells collectstatic where to look for your app's static files.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'shop', 'static'),
]

# --- ⚙️ WHITE NOISE SETTING 3: THE CRUCIAL LINE FOR PRODUCTION ---
# This enables WhiteNoise to compress and serve static files efficiently when DEBUG=False.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
